name: cellflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.26
  - pandas=2.2
  - matplotlib=3.8
  - seaborn=0.13
  - scikit-image=0.22
  - imageio=2.34
  - tqdm=4.66
  - pyyaml=6.0
  - gitpython=3.1
  - tifffile=2024.5
  - opencv
  - typing-extensions
  - fontconfig
  - scikit-learn=1.4
  - openjdk=17
  - ca-certificates
  - nano
  - less
  - vim
  - pytest
  - pip
  - pip:
      - configargparse==1.7
      - torch==2.2.2
      - torchvision==0.17.2
      - torchaudio==2.2.2
      - dill==0.3.8
      - tensorboard==2.16.2
      - imbalanced-learn==0.12.0
      # If conda's opencv doesn't work for pipeline, add this:
      # - opencv-python==4.9.0.80
